### ISSUE TITLE
Extension doesn't work under Thunderbird 57.0b2 (32-bit)

### ISSUE THREAD

**Issue by johnrezzo** [jdgeenen/gcontactsync#112]
Using Thunderbird 57.0b2 (32-bit) the gContactsSync extension seems to be broken. It doesn't sync contacts anymore automatically nor manually. It doesn't show the configured accounts in the preferences. It even breaks the Thunderbird Address Book, which shows an empty (white) window with no contacts listed. Removing the extension restores the address book functionality to normal.

**Comment by jdgeenen** [comment]
Fixed in 2.0.13 (out for review) and 3.0.0a8 (beta channel).  Thanks for writing this up!
