### ISSUE TITLE
Gcontactsync Preferences Dialog Broken in 2.0.13 on macOS TB 59.0a1

### ISSUE THREAD

**Issue by CardBook** [jdgeenen/gcontactsync#113]
Hi Josh

I'm having the same problem on CardBook : https://github.com/CardBook/CardBook/issues/232 ... have you got an idea to fix it ?

Philippe

**Comment by CardBook** [comment]
found it : just add this into your file options.xul
<?xml-stylesheet href="chrome://messenger/skin/preferences/preferences.css"?>

**Comment by jdgeenen** [comment]
@CardBook Thanks!  This will be fixed in the next release.
