### ISSUE TITLE
Unable to add two contacts with the same email address to a group/list

### ISSUE THREAD

**Issue by vfaure7** [jdgeenen/gcontactsync#114]
Hi,

First of all, congratulations for this extension, it's really a great work.

I've found this bug sorting my contacts but i was trying to place a contact in a group and it would not
show up in the matching list in thunderbird. After some digging, I found out that it was because another contact already had the same email address as primary email address.

Here are the steps to reproduce the issue : 

1. Have a group "TestGroup" in google contacts
2. Create a first contact in google contact with email address "test@mytest.com"
3. Add this contact to the group TestGroup
4. Synchronize with Thunderbird to make sure the contact appears in the list TestGroup in thunderbird
5. Create a second contact in google with a different name but the same email address
6. Add this contact to the same group TestGroup
7. Synchronize with Thunderbird

Current Behavior : 
The second contact does not appear in the TestGroup list in thunderbird but it is well synched in the address book 

Expected Behavior : 
The second contact should appear in the TestGroup list in thunderbird

A work around for this is to put another email as the primary email and the contact will appear in the list. Once it's in the list you can put back the correct email address as the primary and it will stay in the list.

I haven't found anything in the log file regarding this issue.

**Comment by jdgeenen** [comment]
This is a limitation of mailing lists in Thunderbird.

**Comment by jdgeenen** [comment]
The recommendation here is to sync each group with a different address book.  There was a plan ~10 years ago to replace the address book and mailing list code, but that still hasn't happened :(.
