### ISSUE TITLE
Port for Thunderbird 60+

### ISSUE THREAD

**Issue by vpontin** [jdgeenen/gcontactsync#115]
Will this be possible?

60+ (currently beta) will incorporate much of quantum philosophy of Firefox to Thunderbird. I currently using it and i would love to see this extension ported as well.

Thanks!

**Comment by jdgeenen** [comment]
This should be addressed by various other issues:
#108, #116, #113, #112

**Comment by jdgeenen** [comment]
#121 will address the remaining major issues.
