### ISSUE TITLE
What does "reset the address book" does?

### ISSUE THREAD

**Issue by mart-e** [jdgeenen/gcontactsync#120]
Hi,

![screenshot from 2018-07-28 08-53-10](https://user-images.githubusercontent.com/564822/43353985-b35ffbd6-9243-11e8-8f23-264023c38c11.png)

This error message is actually kind of scary.
Does "resetting the address book" means: "remove all contacts and start over"?
If yes, this should probably be put clearly in bold.
If not, it should probably be rephrased in a less-scary way (like "reset configuration", ...)

Thank you

**Comment by juanjosv** [comment]
Same here, The reset didn't solve anything. i can only sync using my contacts, i didn't delete any groups nor rename.

**Comment by jdgeenen** [comment]
It deletes your local contacts and groups from Thunderbird and re-pulls them in from Google.
I recommend using the new option to skip synchronization of contacts without e-mail addresses and/or synchronizing each group with a separate address book.
