### ISSUE TITLE
Error in Facebook import. (unsecure connection)

### ISSUE THREAD

**Issue by fedecupe** [jdgeenen/gcontactsync#122]
Trying to import contacts from Facebook yelds the following error
![image](https://user-images.githubusercontent.com/22663905/49029079-1c81cf80-f1a4-11e8-8ca4-c0b3d7fe4f3f.png)

Thunderbird 60.2.1 (64-bit)
gContactSync 3.0.0

**Comment by jdgeenen** [comment]
Dup of #119
