### ISSUE TITLE
Reset Address Book Fails

### ISSUE THREAD

**Issue by bigwave** [jdgeenen/gcontactsync#125]
TypeError: (new Date(...)).toLocaleFormat is not a function[Learn More]  GAddressBook.js:163:8
	GAddressBook_reset chrome://gcontactsync/content/GAddressBook.js:163:8
	Sync_syncGroups chrome://gcontactsync/content/Sync.js:1019:23
	getGroupsSuccess chrome://gcontactsync/content/Sync.js:301:7
	httpReq_readyState chrome://gcontactsync/content/HttpRequest.js:234:11

**Troubleshooting Information from Thunderbird**

Key|Value
-----------|--------------
 Name 	|Thunderbird
Version 	|60.4.0
Build ID 	|20181217101353
Update Channel 	|release
User Agent 	|Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Thunderbird/60.4.0
OS 	|Windows_NT 10.0
Multiprocess Windows 	|0/0 (Disabled)
Stylo 	|content = true (enabled by default), chrome = true (enabled by default)
Google Key 	|Missing
Mozilla Location Service Key 	|Missing
Safe Mode 	|false

**Extensions**

 Name 	|Version 	|Enabled 	|ID
----------|-----------|-----------|---
Account Colors	|11.1	|true	|accountcolors@DW-dev
gContactSync	|3.0.0	|true	|gContactSync@pirules.net
Lightning	|6.2.4	|true	|{e2fda1a4-762b-4020-b5ad-a41df1933103}
Provider for Google Calendar	|4.4.2	|true	|{a62ef8ec-5fdc-40c2-873c-223b8a6925cc}
Thunderbird Conversations	|2.14.6	|true	|gconversation@xulforum.org

**Comment by jdgeenen** [comment]
Thanks, I'm able to recreate this.

**Comment by jdgeenen** [comment]
This is also used in ABOverlay.js

**Comment by jdgeenen** [comment]
Fixed, (though I just noticed the typo in my commit message).  Issue #121 is still a blocker for TB 60+ support.
