### ISSUE TITLE
gContactSync broken in TB nightly 2019-5-27 and later

### ISSUE THREAD

**Issue by jdgeenen** [jdgeenen/gcontactsync#132]
**Describe the bug**
gContactSync broken in TB nightly 2019-5-27 and later ( tested)

The reported error is that createDocument on a XUL element crashes the nightly.

I also hit this in the new account wizard:
`Handler function DebuggerProgressListener.prototype.onWindowCreated threw an exception: TypeError: window is undefined
Stack: getWindowID@resource://devtools/server/actors/targets/browsing-context.js:53:3
DebuggerProgressListener.prototype.onWindowCreated<@resource://devtools/server/actors/targets/browsing-context.js:1575:21
exports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:22
_fireEvent@chrome://global/content/bindings/wizard.xml:413:26
set_currentPage@chrome://global/content/bindings/wizard.xml:89:16
advance@chrome://global/content/bindings/wizard.xml:282:15
connectedCallback/listeners<@chrome://global/content/elements/wizard.js:48:47
EventListener.handleEvent*connectedCallback@chrome://global/content/elements/wizard.js:57:13
LifecycleConnectedCallback*@chrome://global/content/elements/wizard.js:173:16
@chrome://global/content/customElements.js:666:27
@chrome://global/content/customElements.js:682:3
observe@resource://gre/modules/CustomElementsListener.jsm:23:29
Line: 53, column: 3 ThreadSafeDevToolsUtils.js:88:13
    reportException resource://devtools/shared/ThreadSafeDevToolsUtils.js:88
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:115
    _fireEvent chrome://global/content/bindings/wizard.xml:413
    set_currentPage chrome://global/content/bindings/wizard.xml:89
    advance chrome://global/content/bindings/wizard.xml:282
    listeners chrome://global/content/elements/wizard.js:48
    connectedCallback chrome://global/content/elements/wizard.js:57
    <anonymous> chrome://global/content/elements/wizard.js:173
    <anonymous> chrome://global/content/customElements.js:666
    <anonymous> chrome://global/content/customElements.js:682
    observe resource://gre/modules/CustomElementsListener.jsm:23`

**Comment by jdgeenen** [comment]
The AB Dialog has changed so the overlay will need significant work, or to be abandoned completely.

**Comment by jikamens** [comment]
N.B. Check if the AB Dialog is different in TB 68 or those changes are just for TB 69+. If the latter, you may need to have two different versions of the add-on, one for TB 68 and one for later, or have compatibility code in the add-on to handle both. I believe TB 68 has branched in preparation for release so what's on the trunk isn't necessarily going to be in 68.

**Comment by jdgeenen** [comment]
https://developer.thunderbird.net/add-ons/tb68/changes#less-than-dialog-greater-than-events should fix the wizard.  The error I saw is related to the error dialog and shouldn't stop the wizard from working.

**Comment by jdgeenen** [comment]
Next issue:
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWebNavigation.loadURI] browser-custom-element.js:825
    loadURI chrome://global/content/elements/browser-custom-element.js:825
    _wrapURIChangeCall chrome://global/content/elements/browser-custom-element.js:764
    loadURI chrome://global/content/elements/browser-custom-element.js:824
    AccountSetupWizard_loadOAuthPage chrome://gcontactsync/content/AccountSetupWizard.js:202
    gCS_onPageShow chrome://gcontactsync/content/AccountSetupWizard.js:64

**Comment by jdgeenen** [comment]
I'm moving the Account Wizard to #135.  This affects TB 68 and later so I'm working on it first.

**Comment by jdgeenen** [comment]
This should be fixed in 3.1.6.
