### ISSUE TITLE
3.1.6 Blank window when attempting to refresh google authentication tokens

### ISSUE THREAD

**Issue by jikamens** [jdgeenen/gcontactsync#140]
**Describe the bug**
Blank window when attempting to refresh google authentication tokens.

Stack trace in error console:

NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWebNavigation.loadURI] browser-custom-element.js:848
    loadURI chrome://global/content/elements/browser-custom-element.js:848
    _wrapURIChangeCall chrome://global/content/elements/browser-custom-element.js:787
    loadURI chrome://global/content/elements/browser-custom-element.js:847
    onloadListener chrome://gcontactsync/content/gdata.js:474

**To Reproduce**
1. Make sure you have 3.1.6.
2. Restart Thunderbird.
3. Try to sync.
4. It says it has to refresh your auth token.
5. Click OK.
6. Blank window pops up.
7. Observe stack trace in error console.

**Expected behavior**
Auth token is refreshed.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 64-bit
 - Version  19.04

**Application (please complete the following information):**
 - Application: Thunderbird
 - Application Version: Trunk
 - gContactSync Version: 3.1.6

**Comment by jdgeenen** [comment]
Thanks for reporting this.  The fix is in 3.1.7, which I published for review.
