### ISSUE TITLE
preferences menu looks ugly

### ISSUE THREAD

**Issue by patrickdrd** [jdgeenen/gcontactsync#141]
![Clipboard01](https://user-images.githubusercontent.com/24896778/59326610-b992f880-8cef-11e9-8f1f-0564c5f99098.jpg)

 - OS: windows 8.1 x64

 - Application: Thunderbird
 - Application Version: 60.7.0
 - gContactSync Version: 3.0.0a8 (the latest I could install in 60.7.0, the other were reported incompatible)

**Comment by jdgeenen** [comment]
See http://www.pirules.org/blog/?p=490 .  You need to use version 2.1.x on Thunderbird 60.

**Comment by patrickdrd** [comment]
thanks! can I install 2.1.x on top? or should I uninstall first?

**Comment by jdgeenen** [comment]
You can install on top.
