### ISSUE TITLE
duplicated addresses

### ISSUE THREAD

**Issue by Petziboy** [jdgeenen/gcontactsync#145]
Hello,

With the extension gContactSync, how to synchronize my two Thunderbird address books ("personal" and "collected") with Google Contacts without adding twice (in each of my TB address books) the other addresses already contained in my contacts ? ... (ie without creating duplicates)

Example of the problem:

1) Before synchronization:
- Google Contacts: 1000
- TB contacts Personal: 300
- TB contacts collected: 200

2) After Synchronization:
- Google Contacts: 1500 (1000+300+200) ok
- TB contacts Personal : 1500 (300+200+1000) !
- TB contacts collected: 1500 (200+300+1000) !

... So 1500 contacts copied duplicate in Thunderbird (in each directory) .

Thanks for your help! 

**Desktop 
 - OS: MacOS
 - Version 10.13.6

**Application
 - Application: Thunderbird
 - Application Version: 60.8.0
 - gContactSync Version: 2.1.13

**Comment by jdgeenen** [comment]
You should synchronize each of your address books with a separate group/label from Google to avoid this issue.  For example, synchronize Personal with "My Contacts" in Google (which is now called "Contacts" in Gmail) and create a new "Collected" label in Google to synchronize with Thunderbrid's collected address book.
