### ISSUE TITLE
Doesn't sync all contacts from Google account

### ISSUE THREAD

**Issue by fp66** [jdgeenen/gcontactsync#148]
gcontactsync doesn't sync/download all my (375) contacts from my Google account.

Windows 10 Pro
Thunderbird 68.2.2
gcontactsync 3.1.7

**Comment by jdgeenen** [comment]
Do the missing contacts have e-mail addresses?  Newer versions of gContactSync skip contacts without e-mail addresses by default.  You can view and change this setting in the Edit Accounts dialog under the gContactSync menu.  Please also verify you don't have read-only or write-only mode enabled for this address book.

If this isn't the case:
1. Go to the gContactSync Menu -> Preferences -> Main
2. Make sure "Enable Logging", "Enable Verbose Logging" and "Log errors in the Error Console" are checked.
3. Close the dialog
4. Right-click the synchronized address book and click Reset (replace from server).  This will delete your local contacts in Thunderbird and pull them from Google during the next sync.
5. Close Thunderbird (important to avoid various bugs in Thunderbird)
6. Re-open Thunderbird and sync.
7. Did all contacts sync?  Does the synchronization summary appear?
8. Go to the Thunderbird menu -> Tools -> Developer Tools -> Error Console.  Unselect everything except Errors and Warnings.  Take a screenshot or individual copy/paste any errors/warnings here.
9. Go to the gContactSync menuy -> Log.  Check near the bottom for errors.  Copy any errors here (checking for and removing any any personal information first).  If you are willin, please e-mail me the log and reference this issue number.
10. Advanced: In the log, search for a contact that is missing (copy it or open it in your favorite text editor).  You should see it in some XML inside an entry.  This is Google's representation of your contact:

```
<entry gd:etag='&quot;Qnc9eDVSLyt7I2A9XBFQGUwMRw0.&quot;'>
<id>http://www.google.com/m8/feeds/contacts/xxx%40gmail.com/base/e7549518b405393</id>
<updated>2019-11-16T14:54:53.960Z</updated>
<app:edited xmlns:app='http://www.w3.org/2007/app'>2019-11-16T14:54:53.960Z</app:edited>
<category scheme='http://schemas.google.com/g/2005#kind' term='http://schemas.google.com/contact/2008#contact'/>
<title>Jonathan Doe</title>
<link rel='http://schemas.google.com/contacts/2008/rel#photo' type='image/*' href='https://www.google.com/m8/feeds/photos/media/xxx%40gmail.com/e7549518b405393'/>
<link rel='self' type='application/atom+xml' href='https://www.google.com/m8/feeds/contacts/xxx%40gmail.com/full/e7549518b405393'/>
<link rel='edit' type='application/atom+xml' href='https://www.google.com/m8/feeds/contacts/xxx%40gmail.com/full/e7549518b405393'/>
<gd:name>
<gd:fullName>Jonathan Doe</gd:fullName>
<gd:givenName>Jonathan</gd:givenName>
<gd:familyName>Doe</gd:familyName>
</gd:name>
<gd:organization rel='http://schemas.google.com/g/2005#other'>
<gd:orgName>ACME</gd:orgName>
</gd:organization>
<gd:phoneNumber rel='http://schemas.google.com/g/2005#home'>1 23-456-7890</gd:phoneNumber>
<gContact:groupMembershipInfo deleted='false' href='http://www.google.com/m8/feeds/groups/xxx%40gmail.com/base/6'/>
<gContact:groupMembershipInfo deleted='false' href='http://www.google.com/m8/feeds/groups/xxx%40gmail.com/base/2bb3353908984ba0'/>
</entry>
```
You should also see gContactSync decide what to do with it.  Here are a few examples:

```
Skipping Google Contact 'Jonathan Doe' due to skipContactsWithoutEmail
Jane Doe: http://www.google.com/m8/feeds/contacts/xxx%40gmail.com/base/b0c822008b55e4c
 * Found a match, last modified:
   - Google:      1572714759040 (Sat Nov 02 2019 12:12:39 GMT-0500 (Central Daylight Time))
   - Thunderbird: 1573916030000 (Sat Nov 16 2019 08:53:50 GMT-0600 (Central Standard Time))
 * Neither contact has changed
```

**Comment by jdgeenen** [comment]
From the log I received it looks like gContactSync was stopped in the middle of synchronization.  There were no errors in the Error Console.

This could be the "unresponsive script" handling.  Go to the menu -> Options -> Options -> Advanced -> Config Editor.
Type **dom.max_** in the Search box.
Change all three of the settings (max_chrome_script_time, max_ext_content_script_run_time, and max_script_run_time) to 0.  This will disable the setting.  If that doesn't work, try setting it to a large number.
Right-click your address book -> Reset (replace from server)
Restart Thunderbird
Try to sync again.

When finished with the experiment, go back and right-click each setting -> Reset to return them to their original values.

**Comment by fp66** [comment]
Thanks a lot, Josh - now gSC works perfectly again!

I'm so glad that I have my contacts up to date now.

**Comment by jdgeenen** [comment]
@fp66 Was it the "unresponsive script" handling preference?  Would you mind narrowing it down to one of those three prefs?  Reset the max_ext_content_script_run_time and max_script_run_time, leaving just dom.max_chrome_script_run_time alone, then see if the add-on still works (you'll have to Reset your AB again).

**Comment by jdgeenen** [comment]
Also, that setting is supposed to pop up an "Unresponsive Script" warning and give you the option to stop the script or to let it continue.  Did you ever see this warning?

**Comment by fp66** [comment]
No, I haven't seen the warning on Tb yet.

**Comment by jdgeenen** [comment]
This suggestion didn't work for someone else who has seen this issue.

**Comment by jdgeenen** [comment]
Also see Issue #152.  The slow performance in TB 68 likely contributes to this issue.

**Comment by fp66** [comment]
Unfortunately, syncing stopped working properly again. My problems seem to be the same as in https://github.com/jdgeenen/gcontactsync/issues/152 so I continue there.

**Comment by djzgib** [comment]
Try disabling Windows Defender realtime protection!

That worked for me!

**Comment by Mistral-75** [comment]
Disabling Windows Defender real time protection worked for me too.

**Comment by Bastien59960** [comment]
Have to disable windows defender also.... And all my contacts sync perfect.
I'll add an exception for Thunderbird...

**Comment by Bastien59960** [comment]
Exception in windows defender not work...
ANd stopping windows defender not so much, for my 600 contacts adress book it's working but with another account with more than 3000 contacts  it's don't work al all.

Bastien

**Comment by Mistral-75** [comment]
I have 2,063 gmail contacts and disabling Windows Defender's real time protection worked for me.

**Comment by djzgib** [comment]
@Bastien59960 try to disable Windows Defender real-time protection, then exit Thunderbird, re-open it, and then try to sync.

I have noticed that sometimes just disabling real time protection will not work if Thunderbird is already opened, so I need to close it and re-open in order to make sync work. I have around 2000 contacts, and this fix still works for me.

**Comment by Mistral-75** [comment]
> @Bastien59960 try to disable Windows Defender real-time protection, then exit Thunderbird, re-open it, and then try to sync.
> 
> I have noticed that sometimes just disabling real time protection will not work if Thunderbird is already opened, so I need to close it and re-open in order to make sync work. I have around 2000 contacts, and this fix still works for me.

Same here.

**Comment by djzgib** [comment]
For those who wants to continue to use Windows Defender real-time protection along with gContact sync, here is the link to instructions how to exclude thunderbird from real-time protection:

https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/configure-process-opened-file-exclusions-windows-defender-antivirus

Follow these instructions, and just add Thunderbird's path as exlusion (default is C:\Program Files (x86)\Mozilla Thunderbird).

This way, you do not need to disable and re-enable Windows Defender real-time protection each time you want to sync your contacts. Of course, be careful since real-time protection will not scan processes started by Thunderbird.

**Comment by thematicmania** [comment]
I have tried disabling Windows Defender real-time protection and changing the dom.max_* settings, but I cannot sync more than 1200 contacts (with photos).

**Comment by Bastien59960** [comment]
Same here, it's dowloading about 1200 contacts and freeze, with windows 
defender off, and also with windows defender on and exclude path and 
process...


Bastien

Le 26/04/2020 à 18:05, thematicmania a écrit :

**Comment by KrasheninnikovMaxim** [comment]
To exclude Windows Defender, add a folder with logs (C:\Users\<User name>\AppData\Roaming\Thunderbird\Profiles\<Profile name>\gcontactsync).
Or turn off the logs in the Prefernces gContactSync.

**Comment by samsong** [comment]
Since today (14 May 2020) mine is stuck at exactly 1500 contacts then stops. Tried 5 times reset.

I did dom.max settings months ago. not a fix
I tried disable windows defender totally & close/reopen. Still 1500 max.

I think Google API has changed their security maybe???

**Comment by martinsydsin** [comment]
Same issue as Samsong. 841 contacts deleted and only synching exactly 1500. Running TB 60.0.1 and gContactSync 2.1.13. Unlike my other machine which is updated to the release channel this combination worked perfectly fine up to now.
Obviously google has changed something to break the add-on, I will leave this for now and report back in case it gets fixed.

**Comment by samsong** [comment]
Now you said that I think is confirmed. Google is blocking / setting a rate limit on API usage.
Hopefully developer can find the problem & resolve!

**Comment by lucas-berlus** [comment]
Same here with two google accounts - the sync stops at 1.500 contacts.
Ubuntu 16.04 LTS, Thunderbird 68.7.0 (64-Bit), gContactSync  3.1.7

**Comment by thematicmania** [comment]
Mine stops at 1500 as well on three combinations: TB 68 on Ubuntu and Windows, TB 60 on Windows. Reassured that it is not just me.

**Comment by Mistral-75** [comment]
Same here. I used the workaround suggested by KrasheninnikovMaxim, closed and restarted Thunderbird, gContactSync did synchronise and proposed me to delete 631 contacts on the Thunderbird side... 

I have 2,214 contacts in the address book of my Google account and 2,131 in Thunderbird's address books. 2,131 - 631 = 1,500.

**Comment by djzgib** [comment]
Same situation here. I have 3 different laptops, and all of them uses same Google contacts account with gContactSync. This morning, all 3 laprops proposed to delete 483 contacts. I was confused, until I saw latest posts here.

Definitely, there is 1500 contacts limit since today.

Anyone found a solution how to bypass this limit?

**Comment by samsong** [comment]
The plugin hasn't been updated since March.
Probably a google limitation / change due to the exact nature 1500 & being randomly today.
Developer needs to check with google if the API is being limited

**Comment by dantehavershem** [comment]
Well some on OSX ... I have 1781 contacts.. and I got yesterday the message gSyn deletes locally 281 contacts! Google 0 .. now I tried several times to sync, stops at 1500. Same on my win7 laptop... 281 to delete, google 0, it is a nightmare to loose 300 business contacts...

**Comment by JayBird707** [comment]
Just happen to me yesterday lost 2300+ contacts from Thunderbird.  Gut instinct make me agree with Google API revision theroy.
Mint 19.3 tricia
x86_64 Linux 4.15.0-99-generic
ThunderBird 68.7.0 (64-bit)
gContactsync 3.1.7

**Comment by colmode** [comment]
Same behavior here. sync wants to delete the majority of contacts from the local client.
We should file a new bug since this one is closed.

**Comment by colmode** [comment]
See comments starting at https://github.com/jdgeenen/gcontactsync/issues/148#issuecomment-628434390

**Comment by PiPo-Sido** [comment]
> Same behavior here. sync wants to delete the majority of contacts from the local client.
> We should file a new bug since this one is closed.

So the best is to make a export csv file from google contacts before this add-ons is deleting contacts?

**Comment by colmode** [comment]
I just restored abook.mab and abook-1.mab from my backups the first time that the sync blew away my local contacts.

**Comment by JayBird707** [comment]
I restored my abook also and turned off auto sync until this is resolved

**Comment by JayBird707** [comment]
I have backed up my Google Contacts, Exported my gContactSync contacts and saved my abook in a safe place.

**Comment by dantehavershem** [comment]
Well it didn't touch my Google Contacts, somehow it is only removing my local contacts..  
on all platforms the same behavior.

**Comment by JayBird707** [comment]
Agree it is the Google side that is driving deletion on the gContactSync side.

**Comment by KrasheninnikovMaxim** [comment]
Perhaps Google stops syncing at 1500, and gContactSync interprets this as meaning that the rest should be deleted

**Comment by Huku-Huku** [comment]
Here is the new bug related to this issue:
https://github.com/jdgeenen/gcontactsync/issues/156

**Comment by dkelley044** [comment]
Code needs a re-write, google is now returning a max of 1500 contacts per page/request, then you have to use a next URI to retrieve subsequent page(s) of contacts.
Michael Adler just fixed this in his python contact sync script, here's a link to some more info:
https://stackoverflow.com/a/62054304/6492825

**Comment by Krishna5907** [comment]
> 
> 
> Code needs a re-write, google is now returning a max of 1500 contacts per page/request, then you have to use a next URI to retrieve subsequent page(s) of contacts.
> Michael Adler just fixed this in his python contact sync script, here's a link to some more info:
> https://stackoverflow.com/a/62054304/6492825


Dear Can you Tell me how to use this Script to Fix Error
Mail me on Prashantsavaj3975@gmail.com

**Comment by Krishna5907** [comment]
> 
> 
> Since today (14 May 2020) mine is stuck at exactly 1500 contacts then stops. Tried 5 times reset.
> 
> I did dom.max settings months ago. not a fix
> I tried disable windows defender totally & close/reopen. Still 1500 max.
> 
> I think Google API has changed their security maybe???


Dear I had Done Same but nothing is happend. if you get any solution let me know on Prashantsvaj3975@gmail.com

**Comment by Krishna5907** [comment]
> 
> 
> gcontactsync doesn't sync/download all my (375) contacts from my Google account.
> 
> Windows 10 Pro
> Thunderbird 68.2.2
> gcontactsync 3.1.7

I had Synced All My Contacts By update

https://github.com/jdgeenen/gcontactsync/raw/master/downloads/gContactSync-3.2.0.xpi

**Comment by natxosorolla** [comment]
It worked to me (Ubuntu). I had a limit of 1500 contacts. With this update https://github.com/jdgeenen/gcontactsync/raw/master/downloads/gContactSync-3.2.0.xpi (the web has until 3.1.7 version)
