### ISSUE TITLE
Doesn't sync all contacts from Google account

### ISSUE THREAD

**Issue by jpmjpmjpm** [jdgeenen/gcontactsync#167]
**Describe the bug**
From 1708 contacts in my Google account only 1278 are synchronized by gContactSync

**To Reproduce**
1. Look a Google contacts the number of contacts
2. Click on gContactSync + sync memu
3. Look at the gContactSync notification window to see the number of contact synchronized
4. In particular, the contact "RAPHAEL" which has an email address in Google contacts is missing

**Expected behavior**
Have all the 1708 contacts synchronized

**Screenshots**
![google-contacts-summary](https://user-images.githubusercontent.com/22132095/94344978-3fd96800-0023-11eb-8294-484bb7a60530.jpeg)
![gContactSync-notification](https://user-images.githubusercontent.com/22132095/94344980-4536b280-0023-11eb-8a37-50ead37c452b.jpeg)
[gContactSync-log.txt](https://github.com/jdgeenen/gcontactsync/files/5286964/gContactSync-log.txt)

**Desktop**
 - OS: Ubuntu
 - Version 18.04.5 LTS

**Application**
 - Application: Thunderbird
 - Application Version: 68.10.0 (64-bit)
 - gContactSync Version: 3.1.7

**Additional context**
I used [process described](https://github.com/jdgeenen/gcontactsync/issues/148#issuecomment-554644800) in issue #148 to get the log.

Let me know if any additional information could be useful.
Thanks for your support!

**Comment by zanonmark** [comment]
Hi,

the bug was fixed. You need to download the latest version (3.2.0) manually.

Thanks,
MZ

**Comment by jpmjpmjpm** [comment]
Thanks for your support.

Really appreciated!
