### ISSUE TITLE
Switch to OAuth

### ISSUE THREAD

**Issue by jdgeenen** [jdgeenen/gcontactsync#2]
ClientLogin is obsolete and will no longer work in 2015, so v0.5 will switch to OAuth for authentication.  Google can provide a long-term token.

**Comment by kq01526** [comment]
> @jdgeenen wrote in https://github.com/jdgeenen/gcontactsync/issues/2#issue-24671328:
> 
> ClientLogin is obsolete and will no longer work in 2015

This doesn't seem to be true?

You can still enable it via:

https://www.google.com/settings/security/lesssecureapps

So, is there any way to use a normal password with gContactSync? Or is OAuth the only way to use gContactSync now?

Could you please reintroduce a way to use a normal password instead of OAuth?

Regards

**Comment by jdgeenen** [comment]
Version 2.0.0 and later only supports OAuth for authentication.  I just tried signing in with an older version and it failed with a 404 and the text "https://developers.google.com/accounts/docs/AuthForInstalledApps".  If you want to try an older version you can download it [here](https://addons.mozilla.org/en-us/thunderbird/addon/gcontactsync/versions/).

**Comment by kq01526** [comment]
@jdgeenen :

Have you enabled less secure apps via https://www.google.com/settings/security/lesssecureapps before trying to log in?

You first need to be logged in to your Google account (Gmail for example), then open https://www.google.com/settings/security/lesssecureapps, then you will see a page with two radio buttons which will allow you to enable less secure apps.

It is explained over there:

https://support.google.com/accounts/answer/6010255

Does it work when enabling less secure apps?

PS: "Less secure apps" are apps which do not support OAuth and require login via username and password.

**Comment by jdgeenen** [comment]
Yes, I have less secure app authentication enabled, but I don't think it applies to the unsupported [ClientLogin](https://developers.google.com/identity/protocols/AuthForInstalledApps) (the alternative to OAuth).

**Comment by kq01526** [comment]
Okay, thank you for having looked into this.
