### ISSUE TITLE
"Please login before trying to sync contacts" message when canceling the expired token prompt

### ISSUE THREAD

**Issue by jdgeenen** [jdgeenen/gcontactsync#23]
In version 0.4 canceling the expired token prompt causes a "Please login before trying to sync contacts" message which 1) isn't very helpful and 2) isn't necessary.

I believe this can be fixed by only removing the auth token on successful authentication.

**Comment by pcav** [comment]
I also have this problem. I keep on getting:

Error encountered while authenticating.
Please make sure you typed your e-mail address and password correctly
and that your e-mail address is valid.

I'm pretty sure my credentials are OK.
