### ISSUE TITLE
Warn if OAuth port already in use

### ISSUE THREAD

**Issue by cowwoc** [jdgeenen/gcontactsync#74]
Following up on #68, please try checking if the configured port is already in use (at runtime) and provide a warning dialog asking the user to change the configured port. Otherwise users will have a hard time figuring out the problem. In my case, port 80 contains a web server that redirects to http://www.google.com/. I would have never figured out what was going on unless I stumbled upon #68 by luck scanning your commit log.

**Comment by jdgeenen** [comment]
I reimplemented #68 to no longer use a redirect so this is no longer necessary.
