### ISSUE TITLE
Throttle photo downloads

### ISSUE THREAD

**Issue by jdgeenen** [jdgeenen/gcontactsync#80]
gContactSync needs to throttle photo downloads: http://pirules.org/forum/index.php/topic,644.0.html

**Comment by TimMensch** [comment]
I'm not sure if it's related, but I saw a lot of photos fail to download in the log, and I'm missing a lot of contacts from a clean download/sync from Google.

**Comment by digitalcircuit** [comment]
Until rate-limiting is properly implemented, it's possible to work around this issue by forcing gContactSync to repeatedly synchronize unchanged contacts every minute until all photos are downloaded.

Edit [line 102 of SyncWorker.js](https://github.com/jdgeenen/gcontactsync/blob/7c90300d7988546a31c7e04efc0827d148e6fb1f/src/content/SyncWorker.js#L102) from:
```javascript
else if (gCardDate > aData.mLastSync) {
```
To:
```javascript
else if (true) {
```
Then set gContactSync's automatic Synchronize Interval to 1 minute.  Once the log stops showing 503 errors for photo downloads, undo the changes above.
Note: you may lose any changes made to contacts from Thunderbird if they are not already updated in Google.

**Comment by jdgeenen** [comment]
Can anyone confirm that this is fixed in 2.0.5?

**Comment by bmatzelle** [comment]
@jdgeenen I'm a new user to gContactSync, I used [Google Contacts](https://addons.mozilla.org/en-US/thunderbird/addon/google-contacts/) previously, and I just installed 2.0.5 yesterday.  Unfortunately it doesn't load any photos for me.  I activated verbose logging and stored the log file.  Would you like me to send you part of it for debugging purposes?  I'd rather not upload the whole file here because it has a lot of work contact information in it.  

**Plugin Configuration:**

- Two accounts: Gmail and Google Apps
- Both set to "Read-only"
- Both have "Local changes have priority over remote changes" unchecked

**My specs:**

OS X Yosemite - 10.10.3
Thunderbird 31.7.0
gContactSync 2.0.5

**Comment by bmatzelle** [comment]
@jdgeenen So is this issue unrelated?  Should I post about it somewhere else?

**Comment by S71WE** [comment]
same here on windows 7 Prof. and Linux Mint. No photos will be synced.

**Comment by jdgeenen** [comment]
@bmatzelle @S71WE, could you use the report form or e-mail me the log file after turning on verbose logging? http://www.pirules.org/extensions/submit_error.php?ext=gContactSync

**Comment by jdgeenen** [comment]
Just found a copy/paste mistake related to read-only mode, so if you both have read-only mode set I don't need a lot.  See Issue #85.  I'll release 2.0.6 this week with the fix.

**Comment by bmatzelle** [comment]
Thanks Josh. I'll send it to you tomorrow.

On Sunday, June 14, 2015, Josh Geenen <notifications@github.com> wrote:

> Just found a copy/paste mistake related to read-only mode, so if you both
> have read-only mode set I don't need a lot. See Issue #85. I'll release
> 2.0.6 this week with the fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jdgeenen/gcontactsync/issues/80#issuecomment-111837972>
> .
>


-- 
Sent from my iPhone

**Comment by bmatzelle** [comment]
@jdgeenen Submitted.  Thanks Josh.  Your plugin is fantastic BTW.  Well done.

**Comment by thematicmania** [comment]
Hi. Thanks for gcontactsync. Do you know when 2.0.6 will be released addressing this mistake? Thanks.

**Comment by jdgeenen** [comment]
I ran into a bug on addons.mozilla.org when trying to submit my add-on so I'm waiting for the fix to be pushed (https://bugzilla.mozilla.org/show_bug.cgi?id=1194198).  After it is submitted I'll also have to wait for it to be reviewed.

In the meantime you can find 2.0.6 here: https://github.com/jdgeenen/gcontactsync/blob/2.0/downloads/gContactSync-2.0.6.xpi?raw=true

**Comment by thematicmania** [comment]
Thanks. Much appreciated.
      
      On 01/09/15 13:55, Josh Geenen wrote:
    
    
      I ran into a bug on addons.mozilla.org when trying to submit my
        add-on so I'm waiting for the fix to be pushed (https://bugzilla.mozilla.org/show_bug.cgi?id=1194198).
        After it is submitted I'll also have to wait for it to be
        reviewed.
      In the meantime you can find 2.0.6 here: https://github.com/jdgeenen/gcontactsync/blob/2.0/downloads/gContactSync-2.0.6.xpi?raw=true
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    
    -- 
      
      Stephen Cowley
        
        Address: Dr Stephen J. Cowley, 37 Porson Road, Cambridge CB2
        8ET, UK
        Phone: +44 (0)1223 740712           Email: Stephen@cowley-lam.org.uk

**Comment by jdgeenen** [comment]
2.0.6 has been up for a while with the fix.
