### ISSUE TITLE
Downloadable binaries are not up to date anymore

### ISSUE THREAD

**Issue by rakotomandimby** [jdgeenen/gcontactsync#89]
https://addons.mozilla.org/en-US/thunderbird/addon/gcontactsync/ publishes a 2.0.5 but in the downloads section here, we're stuck at 2.0.1.

**Comment by jdgeenen** [comment]
You can find downloads for 2.0.x in the 2.0 branch:
https://github.com/jdgeenen/gcontactsync/tree/2.0/downloads

**Comment by rakotomandimby** [comment]
Thank you
